### ISSUE TITLE
Button is always visible / JS build seems out of date

### ISSUE THREAD

**Issue by PRGfx** [psmb/Psmb.SplitAdd#6]
While the [source](https://github.com/psmb/Psmb.SplitAdd/blob/21021a9cb0bcf526560efa0cbca05f2b82634549/Resources/Private/SplitAdd/src/manifest.js#L23) uses the plow function to determinate whether the button should be visible, the [compiled code](https://github.com/psmb/Psmb.SplitAdd/blob/21021a9cb0bcf526560efa0cbca05f2b82634549/Resources/Public/JavaScript/SplitAdd/Plugin.js#L1539) always just returns `true`.

Using the button when it is not really enabled, throws an exception.

I installed and built the plugin locally and the compiled code changes to what I would expect, so I think the repository code is out of date.
However since dependencies aren't locked, I'm hesitant to just PR a new build, as some other `neos-ui-extensibility` might break something for older neos installations?

**Comment by lorenzulrich** [comment]
Hi @PRGfx 

Did you ever create a new JS build? With which Neos version would it be compatible? Since currently only 7.3+ is supported, the Neos constraints could just be raised if that's a problem.

**Comment by PRGfx** [comment]
Hi @lorenzulrich,
I made a fork at the time and it worked iirc, but I didn't want to PR the new lock file.
https://github.com/mindscreen/Psmb.SplitAdd/commit/8f022402a42b9fbb8faaa57234323b5fda6e1efa

I don't know if it still works, especially with plugins requiring a new build for 8.2+ in some way.. - it should probably get a fresh build. To think ahead, one could probably get rid of plow-js as it is not included in newer ui versions. Not sure about other dependencies, cke updates etc

**Comment by lorenzulrich** [comment]
@mhsdesign As one of the Neos UI developers, could you give us some insight here? What needs to be done for this package to be "officially working" with supported Neos UI versions?

**Comment by mhsdesign** [comment]
Hi yes sure ;)

I would suggest to raise the supported "neos-ui" versions via composer to at least 7.3, if not 8.2 or better 8.3 to be totally safe. There is no need in supporting ancient legacy systems.

Second we should use the new 8.3 neos-ui-extensibility-webpack-adapter or even esbuild and replace plow js with native javascript code.

Then commit the lock file and the build PRODUCTION artifacts - currently bundle size is too big and not minified.

If you need help with this i might be up for it in January and always happy to review ;)

P.S. For help of the Neos Psmb packages it is a good idea to raise somehow attention in slack or via ping as dmitri is currently not working on Neos anymore ;)

**Comment by PRGfx** [comment]
I updated the build-stack as discussed.
@mhsdesign maybe you can share your thoughts on the neos-ui-extensibility version vs. the neos versions we can permit in the composer.json.
Happy to make additional adjustments if something comes to mind.

**Comment by mhsdesign** [comment]
Wow thank you so much :) Yes ill answer in the PR!

**Comment by mhsdesign** [comment]
Fyi the isVisible feature newer worked until your compile, as after its introduction https://github.com/psmb/Psmb.SplitAdd/commit/b1beafdba7913374a303a13ba7b769fa57cc3a34 the sources were never recompiled.

**Comment by mhsdesign** [comment]
The bugfix ~should~ _will_ also fix that the icon is visible even for nodes which dont have inline edit mode:

<img width="415" alt="image" src="https://github.com/psmb/Psmb.SplitAdd/assets/85400359/0d8fb4c0-fa11-4661-a920-43a6a0cebe83">
